### ISSUE TITLE
Option for HI subs

### ISSUE THREAD

**Issue by IsusVonBier** [radixdev/subtitle-renamer-scripts#2]
There are often "2_English" and "3_Engliish" subs, It would be nice to have an option to choose HI subs.
You could choose by file size.

Edit: Also there are sometimes subs for non-english parts only, you could also solve this by setting some size limit

**Comment by radixdev** [comment]
Can you give a full example of what the subtitle files should map to? I.e. 2_english is "en", 3_english is "sdh.en", etc. Or give me a way to know which file sizes correspond to which type of files. I.e. sdh is the second biggest, "non English parts only" is the smallest, etc.

**Comment by IsusVonBier** [comment]
For example:

![2022-06-20_18-11-55](https://user-images.githubusercontent.com/48519578/174642847-160020e6-525a-42b0-a895-82f57876ddc8.png)

And about mapping, I always use SDH if available as ".en.srt", but I guess that's a matter of preference.
You could make optional flags like:
    1) copy both as ".en" and ".en.sdh"
    2) copy only SDH as ".en"
    3) copy only SDH as ".en.sdh"

**Comment by radixdev** [comment]
I think the easiest solution would be to just sort them based on the file sizes available and create those three extensions based on the sizes. Then the user can just select in their media player which subtitle to use. This wouldn't require the use of flags. Thanks for the screenshot!
